[package]
name = "zinfo"
version = "0.3.0"
edition = "2021"
authors = ["Maxwell Anderson <zaechus@proton.me>"]
license = "MIT"
repository = "https://github.com/Zaechus/zinfo"
description = "A cross-platform system information program"
exclude = ["justfile", ".github"]

[dependencies]
crossterm = "0.26"

[profile.release]
panic = "abort"
strip = true
