[package]
name = "zinfo"
version = "0.2.5"
edition = "2021"
authors = ["Maxwell Anderson <zaechus@proton.me>"]
license = "MIT"
repository = "https://github.com/Zaechus/zinfo"
description = "A small system information program"
exclude = ["assets", "justfile"]

[dependencies]
crossterm = "0.25"

[profile.release]
strip = true
