[package]
name = "zinfo"
version = "0.2.5"
edition = "2021"
authors = ["Maxwell Anderson <maxwell.anderson.public@protonmail.com"]
license = "MIT"
repository = "https://github.com/Zaechus/zinfo"
description = "A small system information program"
exclude = [".github", "assets", "justfile", "shell.nix"]

[dependencies]
crossterm = "0.25"

[profile.release]
strip = true
